import { fromJS } from 'immutable';

const naturesConfig = fromJS(
  [
    {
      name: '勤奋',
      key: 0,
      value: 'HARDY',
      dislike: '无',
      like: '无',
      ivs: [1, 1, 1, 1, 1, 1],
    },
    {
      name: '坦率',
      key: 1,
      value: 'DOCILE',
      dislike: '无',
      like: '无',
      ivs: [1, 1, 1, 1, 1, 1],
    },
    {
      name: '害羞',
      key: 2,
      value: 'BASHFUL',
      dislike: '无',
      like: '无',
      ivs: [1, 1, 1, 1, 1, 1],
    },
    {
      name: '浮躁',
      key: 3,
      value: 'QUIRKY',
      dislike: '无',
      like: '无',
      ivs: [1, 1, 1, 1, 1, 1],
    },
    {
      name: '认真',
      key: 4,
      value: 'SERIOUS',
      dislike: '无',
      like: '无',
      ivs: [1, 1, 1, 1, 1, 1],
    },
    {
      name: '怕寂寞',
      key: 5,
      value: 'LONELY',
      dislike: '酸',
      like: '辣',
      ivs: [1, 1.1, 0.9, 1, 1, 1],
    },
    {
      name: '固执',
      key: 6,
      value: 'ADAMANT',
      dislike: '涩',
      like: '辣',
      ivs: [1, 1.1, 1, 0.9, 1, 1],
    },
    {
      name: '顽皮',
      key: 7,
      value: 'NAUGHTY',
      dislike: '苦',
      like: '辣',
      ivs: [1, 1.1, 1, 1, 0.9, 1],
    },
    {
      name: '勇敢',
      key: 8,
      value: 'BRAVE',
      dislike: '甜',
      like: '辣',
      ivs: [1, 1.1, 1, 1, 1, 0.9],
    },
    {
      name: '大胆',
      key: 9,
      value: 'BOLD',
      dislike: '辣',
      like: '酸',
      ivs: [1, 0.9, 1.1, 1, 1, 1],
    },
    {
      name: '淘气',
      key: 10,
      value: 'IMPISH',
      dislike: '涩',
      like: '酸',
      ivs: [1, 1, 1.1, 0.9, 1, 1],
    },
    {
      name: '乐天',
      key: 11,
      value: 'LAX',
      dislike: '苦',
      like: '酸',
      ivs: [1, 1, 1.1, 1, 0.9, 1],
    },
    {
      name: '悠闲',
      key: 12,
      value: 'RELAXED',
      dislike: '甜',
      like: '酸',
      ivs: [1, 1, 1.1, 1, 1, 0.9],
    },
    {
      name: '内敛',
      key: 13,
      value: 'MODEST',
      dislike: '辣',
      like: '涩',
      ivs: [1, 0.9, 1, 1.1, 1, 1],
    },
    {
      name: '慢吞吞',
      key: 14,
      value: 'MILD',
      dislike: '酸',
      like: '涩',
      ivs: [1, 1, 0.9, 1.1, 1, 1],
    },
    {
      name: '马虎',
      key: 15,
      value: 'RASH',
      dislike: '苦',
      like: '涩',
      ivs: [1, 1, 1, 1.1, 0.9, 1],
    },
    {
      name: '冷静',
      key: 16,
      value: 'QUIET',
      dislike: '甜',
      like: '涩',
      ivs: [1, 1, 1, 1.1, 1, 0.9],
    },
    {
      name: '温和',
      key: 17,
      value: 'CALM',
      dislike: '辣',
      like: '苦',
      ivs: [1, 0.9, 1, 1, 1.1, 1],
    },
    {
      name: '温顺',
      key: 18,
      value: 'GENTLE',
      dislike: '酸',
      like: '苦',
      ivs: [1, 1, 0.9, 1, 1.1, 1],
    },
    {
      name: '慎重',
      key: 19,
      value: 'CAREFUL',
      dislike: '涩',
      like: '苦',
      ivs: [1, 1, 1, 0.9, 1.1, 1],
    },
    {
      name: '自大',
      key: 20,
      value: 'SASSY',
      dislike: '甜',
      like: '苦',
      ivs: [1, 1, 1, 1, 1.1, 0.9],
    },
    {
      name: '胆小',
      key: 21,
      value: 'TIMID',
      dislike: '辣',
      like: '甜',
      ivs: [1, 0.9, 1, 1, 1, 1.1],
    },
    {
      name: '急躁',
      key: 22,
      value: 'HASTY',
      dislike: '酸',
      like: '甜',
      ivs: [1, 1, 0.9, 1, 1, 1.1],
    },
    {
      name: '爽朗',
      key: 23,
      value: 'JOLLY',
      dislike: '涩',
      like: '甜',
      ivs: [1, 1, 1, 0.9, 1, 1.1],
    },
    {
      name: '天真',
      key: 24,
      value: 'NAIVE',
      dislike: '苦',
      like: '甜',
      ivs: [1, 1, 1, 1, 0.9, 1.1],
    },
  ],
);

export {
  naturesConfig,
};
